version: "3.8"
services:
  node-red-group1:
    image: nodered/node-red:latest
    ports: 
      - "1880:1880"
    networks:
      - group1_net
    volumes:
      - group1_nodered_vol:/data

  influxdb-group1:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - group1_net
    volumes:
      - group1_influx_vol:/var/lib/influxdb2:rw  

  grafana-group1:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - group1_net
    volumes:
      - group1_grafana_vol:/var/lib/grafana:rw  

  mqtt-group1:
    image: eclipse-mosquitto:1.6.13
    ports:
      - "50313:1883"
    networks:
      - group1_net
   
volumes:
  group1_nodered_vol:  
  group1_influx_vol:
  group1_grafana_vol:

networks:
  group1_net: 

